# Numpy = Numerical Python

In [1]:
#perhitungan kompleks dapat diselesaikan dengan cepat (mempermudah)
#menggunakan pendekatan array programming
#dapat menangani aljabar linier, perkalian matriks, dsb
#Numpy dirilis pada tahun 2006 yang digunakan untuk mempermudah 

## Struktur data array

### List

In [3]:
import numpy as np
np.__version__

'1.24.3'

In [4]:
gpas_as_list = [4.0, 3.2, 3.5]

In [5]:
#menambahkan value pada list
gpas_as_list.append(4.0)
gpas_as_list

[4.0, 3.2, 3.5, 4.0]

In [6]:
gpas_as_list.insert(1, "belum ada")
gpas_as_list

[4.0, 'belum ada', 3.2, 3.5, 4.0]

In [9]:
gpas_as_list.pop(1)
gpas_as_list

[4.0, 3.5, 4.0]

In [8]:
gpas_as_list

[4.0, 3.2, 3.5, 4.0]

### Array

In [10]:
gpas = np.array(gpas_as_list)

In [11]:
gpas

array([4. , 3.5, 4. ])

In [12]:
#cek tipe data
gpas.dtype

dtype('float64')

In [13]:
#cek terdapat berapa element
gpas.size

3

## Study Log

In [17]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

In [18]:
%whos

Variable        Type       Data/Info
------------------------------------
autopep8        module     <module 'autopep8' from '<...>e-packages\\autopep8.py'>
gpas            ndarray    3: 3 elems, type `float64`, 24 bytes
gpas_as_list    list       n=3
json            module     <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
np              module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes


## Array Multidimensi

In [19]:
students_gpas = np.array([
    [4.0, 3.3, 3.5, 4.0],
    [3.96, 3.92, 4.0, 4.0],
    [3.2, 3.8, 4.0, 4.0]
], np.float16)
students_gpas

array([[4.  , 3.3 , 3.5 , 4.  ],
       [3.96, 3.92, 4.  , 4.  ],
       [3.2 , 3.8 , 4.  , 4.  ]], dtype=float16)

In [20]:
#melihat dimensinya
students_gpas.ndim

2

In [21]:
students_gpas.shape
#jdi pada array terdapat 3 student dengan 4 element

(3, 4)

In [22]:
students_gpas[2]

array([3.2, 3.8, 4. , 4. ], dtype=float16)

In [25]:
students_gpas[2][3]

4.0

## Indexing Array MultiDimensi

In [26]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])
study_minutes.shape

(2, 100)

In [27]:
study_minutes[1][0] = 60
study_minutes

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [60,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0]], dtype=uint16)

In [29]:
#membuat nilai random
rand = np.random.RandomState(42)
fake_log = rand.randint(30, 180, size = 100, dtype = np.uint16)
fake_log

array([132, 122, 128,  44, 136, 129, 101,  95,  50, 132, 151,  64, 104,
       175, 117, 146, 139, 129, 133, 176,  98, 160, 179,  99,  82, 142,
        31, 106, 117,  56,  98,  67, 121, 159,  81, 170,  31,  50,  49,
        87, 179,  51, 116, 177, 118,  78, 171, 117,  88, 123, 102,  44,
        79,  31, 108,  80,  59, 137,  84,  93, 155, 160,  67,  80, 166,
       164,  70,  50, 102, 113,  47, 131, 161, 118,  82,  89,  81,  43,
        81,  38, 119,  52,  82,  31, 159,  57, 113,  71, 121, 140,  91,
        70,  37, 106,  64, 127, 110,  58,  93,  79], dtype=uint16)

In [33]:
[fake_log[21], fake_log[1]]

[160, 122]

In [35]:
fake_log[[1, 21]]

array([122, 160], dtype=uint16)

In [36]:
#membuat array baru berdasarkan nilai pada array sebelumnya.
index = np.array([
    [1, 21],
    [1, 2]
])
fake_log[index]

array([[122, 160],
       [122, 128]], dtype=uint16)

In [37]:
study_minutes = np.append(study_minutes, [fake_log])
study_minutes

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  60,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   