In [1]:
import math
import statistics as st 
import numpy as np
import scipy.stats
import pandas as pd

# Mean

In [2]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]
print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [3]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)
print(y)
print(y_with_nan)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [4]:
mean = sum(x)/len(x)
mean

8.7

In [5]:
mean_=st.mean(x)
mean_

8.7

In [6]:
mean_ = np.mean(y)
mean_

8.7

In [7]:
#jika terdapat nilai nan maka hasilnya akan muncul nan
print(np.mean(y_with_nan))
print(y_with_nan.mean())

nan
nan


In [8]:
#mengabaikan nilai nan
np.nanmean(y_with_nan)

8.7

In [9]:
z.mean()

8.7

In [10]:
z_with_nan.mean()

8.7

## Weighted Mean
mencari bobot angka pada data

In [11]:
.2 * 2 + .5 * 4 + .3 * 8

4.8

In [12]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [.1, .2, .3, .25, .15]
wmean1 = sum(w[i] * x[i] for i in range(len(x))) / sum(w)
wmean1

6.95

In [13]:
wmean2 = sum(w_ * x_ for w_, x_ in zip(w, x)) / sum(w)
wmean2

6.95

In [14]:
y, z, w = np.array(x), pd.Series(x), np.array(w)
wmean_arr = np.average(y, weights=w)
wmean_arr

6.95

In [15]:
wmean_ser = np.average(x, weights=w)
wmean_ser

6.95

In [16]:
(w * y).sum() / w.sum()

6.95

## Harmonic Mean

In [17]:
hmean = len(x) / sum(1/value for value in x)
hmean

2.7613412228796843

In [18]:
hmean = st.harmonic_mean(x)
hmean

2.7613412228796843

In [19]:
scipy.stats.hmean(y)

2.7613412228796843

In [20]:
scipy.stats.hmean(z)

2.7613412228796843

## Geometric Mean

In [21]:
gmean = 1 
for item in x:
    gmean *= item
    
gmean **= 1/len(x)
gmean

4.677885674856041

In [22]:
scipy.stats.gmean(y)

4.67788567485604

In [23]:
scipy.stats.gmean(z)

4.67788567485604

# Median

In [24]:
#ganjil
n = len(x)

if n%2 :
    median = sorted(x)[round(0.5*(n-1))]
    
median

4

In [25]:
#genap
n = len(x)

if n%2 :
    median = sorted(x)[round(0.5*(n-1))]
else :
    x_ord, index = sorted(x), round(0.5*n)
    median = 0.5 * (x_ord[index-1] + x_ord[index])
median

4

In [26]:
x

[8.0, 1, 2.5, 4, 28.0]

In [27]:
sorted(x)

[1, 2.5, 4, 8.0, 28.0]

In [28]:
#menghilangkan outlier
sorted(x[:-1])

[1, 2.5, 4, 8.0]

In [29]:
st.median_low(x[:-1])

2.5

In [30]:
st.median_high(x[:-1])

4

In [31]:
median = np.median(y)
median

4.0

In [32]:
y

array([ 8. ,  1. ,  2.5,  4. , 28. ])

In [33]:
median = np.median(y[:-1])
median

3.25

# Mode/Modus

In [34]:
u = [2, 3, 2, 8, 12]
v = [12, 15, 12, 15, 21, 15, 12]

In [35]:
mode = max((u.count(item), item) for item in set(u))[1]
mode

2

In [36]:
mode = st.mode(u)
mode

2

In [37]:
u_arr, v_arr = np.array(u), np.array(v)

In [38]:
mode = scipy.stats.mode(u)
mode

ModeResult(mode=2, count=2)

In [39]:
#untuk mengetahui banyak data yang keluar
mode = scipy.stats.mode(v)
mode

ModeResult(mode=12, count=3)

In [40]:
mode.mode

12

In [41]:
mode.count

3

In [42]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

In [43]:
print(u.mode())
print(v.mode())
print(w.mode())

0    2
dtype: int64
0    12
1    15
dtype: int64
0    2.0
dtype: float64


# Measure of Variability
## Variance

In [44]:
n = len(x)
mean = sum(x) / n
var = sum((item - mean)**2 for item in x)/(n - 1)
var

123.19999999999999

In [45]:
var = st.variance(x)
var

123.2

In [46]:
#ddof untuk menyetel degrees of freedom ke 1 untuk memungkinakan kalkulasi yang tepat dari s^2
var = np.var(y, ddof=1)
var

123.19999999999999

In [47]:
y.var(ddof=1)

123.19999999999999

In [48]:
z.var(ddof=1)

123.19999999999999

In [49]:
z.var()

123.19999999999999

## Standard Deviation
akar dari variance

In [50]:
std = var ** .5
std

11.099549540409285

In [51]:
st.stdev(x)

11.099549540409287

In [52]:
#fungsi
np.std(y, ddof=1)

11.099549540409285

In [53]:
#method
y.std(ddof=1)

11.099549540409285

In [54]:
y_with_nan.std(ddof=1)

nan

In [55]:
#untuk mengabaikan nan
np.nanstd(y_with_nan, ddof=1)

11.099549540409285

In [56]:
z.std()

11.099549540409285

In [57]:
#untuk populasi
st.pstdev(x)

9.927738916792686

In [58]:
#numpy
print(np.std(y, ddof=0))
print(y.std(ddof=0))

9.927738916792684
9.927738916792684


In [59]:
z.std(ddof=0)

9.927738916792684

## Skewness

In [60]:
x = [8.0, 1, 2.5, 4, 28.0]
n = len(x)
mean = sum(x) / n
var = sum((item - mean)**2 for item in x) / (n-1)
std = var**0.5
skew = (sum((item - mean)**3 for item in x)* n/ ((n-1)*(n-2)* std**3))
skew

1.9470432273905929

In [61]:
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [62]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [63]:
z.skew()

1.9470432273905924

In [64]:
print(scipy.stats.skew.__doc__)

    


Compute the sample skewness of a data set.

For normally distributed data, the skewness should be about zero. For
unimodal continuous distributions, a skewness value greater than zero means
that there is more weight in the right tail of the distribution. The
function `skewtest` can be used to determine if the skewness value
is close enough to zero, statistically speaking.

Parameters
----------
a : ndarray
    Input array.
axis : int or None, default: 0
    If an int, the axis of the input along which to compute the statistic.
    The statistic of each axis-slice (e.g. row) of the input will appear in a
    corresponding element of the output.
    If ``None``, the input will be raveled before computing the statistic.
bias : bool, optional
    If False, then the calculations are corrected for statistical bias.
nan_policy : {'propagate', 'omit', 'raise'}
    Defines how to handle input NaNs.
    
    - ``propagate``: if a NaN is present in the axis slice (e.g. row) along
      whi

In [65]:
z_with_nan.skew()

1.9470432273905924

## Percentile

In [66]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]

In [67]:
st.quantiles(x, n=2)

[8.0]

In [68]:
y = np.array(x)
np.percentile(y, 5)

-3.44

In [69]:
np.percentile(y, 95)

34.919999999999995

In [70]:
np.percentile(y, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [71]:
y_with_nan = np.insert(y, 2, np.nan)

In [72]:
y_with_nan

array([-5. , -1.1,  nan,  0.1,  2. ,  8. , 12.8, 21. , 25.8, 41. ])

In [73]:
np.nanpercentile(y_with_nan, [25, 50, 75])

array([ 0.1,  8. , 21. ])

In [74]:
z, z_with_nan = pd.Series(y), pd.Series(y_with_nan)
z.quantile(0.05)

-3.44

In [75]:
z.quantile([.25, .50, .75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

In [76]:
z_with_nan.quantile([.25, .50, .75])

0.25     0.1
0.50     8.0
0.75    21.0
dtype: float64

## Ranges

In [77]:
np.ptp(y)

46.0

In [78]:
np.ptp(z)

46.0

In [79]:
np.ptp(y_with_nan)

nan

In [80]:
np.ptp(z_with_nan)

nan

In [81]:
np.amax(y) - np.amin(y)

46.0

In [82]:
np.nanmax(y_with_nan) - np.nanmin(y_with_nan)

46.0

In [85]:
z_with_nan

0    -5.0
1    -1.1
2     NaN
3     0.1
4     2.0
5     8.0
6    12.8
7    21.0
8    25.8
9    41.0
dtype: float64

In [83]:
y.max() - y.min()

46.0

In [86]:
z_with_nan.max() - z_with_nan.min

TypeError: unsupported operand type(s) for -: 'float' and 'method'

In [87]:
# Interquartile range
quartiles = np.quantile(y, [0.25, 0.75])
quartiles[1] - quartiles[0]

20.9

In [88]:
quartiles = z.quantile([0.25, 0.75])
quartiles[0.75] - quartiles[0.25]

20.9

In [89]:
# Summary of Descriptive Statistics
result = scipy.stats.describe(y, ddof=1, bias=False)
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [90]:
result.nobs

9

In [91]:
result.minmax[0]

-5.0

In [92]:
result.minmax[1]

41.0

In [93]:
result.mean

11.622222222222222

In [94]:
result.variance

228.75194444444446

In [95]:
result.skewness

0.9249043136685094

In [96]:
result.kurtosis

0.14770623629658886

In [97]:
result = z.describe()
result

count     9.000000
mean     11.622222
std      15.124548
min      -5.000000
25%       0.100000
50%       8.000000
75%      21.000000
max      41.000000
dtype: float64

In [98]:
result['mean']

11.622222222222222

In [99]:
result['std']

15.12454774346805

In [100]:
result['min']

-5.0

In [101]:
result['max']

41.0

In [102]:
result['25%']

0.1

In [103]:
result['50%']

8.0

In [104]:
result['75%']

21.0

# Measures of Correlation Between Pairs of Data

In [105]:
x = list(range(-10, 11))
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]

In [106]:
x_arr, y_arr = np.array(x), np.array(y)
x_ser, y_ser = pd.Series(x_arr), pd.Series(x_arr)

## Covariance 

In [107]:
n = len(x)
mean_x, mean_y = sum(x)/n, sum(y)/n
cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) for k in range(n))
         / (n-1))
cov_xy

19.95

In [108]:
cov_matrix = np.cov(x_arr, y_arr)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [109]:
x_arr.var(ddof=1)

38.5

In [110]:
y_arr.var(ddof=1)

13.914285714285711

In [111]:
cov_xy = cov_matrix[0, 1]
cov_xy

19.95

In [112]:
cov_xy = cov_matrix[1, 0]
cov_xy

19.95

## Correlation Coefficient

In [113]:
var_x = sum((item - mean_x)**2 for item in x)/(n-1)
var_y = sum((item - mean_y)**2 for item in y)/(n-1)
std_x, std_y = var_x ** 0.5, var_y ** 0.5
r = cov_xy / (std_x * std_y)
r

0.861950005631606

In [114]:
r, p = scipy.stats.pearsonr(x_arr, y_arr)
r

0.8619500056316061

In [115]:
p

5.122760847201132e-07

In [116]:
# menerapkan .corrcoef() dengan x_arr dan y_arr sebagai argumen
corr_matrix = np.corrcoef(x_arr, y_arr)
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

In [117]:
r = corr_matrix[0, 1]
r

0.8619500056316061

In [118]:
r = corr_matrix[1, 0]
r

0.861950005631606

In [119]:
scipy.stats.linregress(x_arr, y_arr)

LinregressResult(slope=0.5181818181818181, intercept=5.714285714285714, rvalue=0.861950005631606, pvalue=5.122760847201164e-07, stderr=0.06992387660074979, intercept_stderr=0.4234100995002589)

In [120]:
result = scipy.stats.linregress(x_arr, y_arr)
r = result.rvalue
r

0.861950005631606

In [121]:
r = x_ser.corr(y_ser)
r

1.0

In [122]:
r = y_ser.corr(x_ser)
r

1.0

## Working with 2D Data
example : database tables, csv files, excel, calc and Google spreadsheets

In [123]:
# Axes
a = np.array([[1, 1, 1],
            [2, 3, 1],
            [4, 9, 2],
            [8, 27, 4],
            [16, 1, 1]])
a

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [124]:
np.mean(a)

5.4

In [125]:
a.mean()

5.4

In [126]:
np.median(a)

2.0

In [127]:
a.var(ddof=1)

53.40000000000001

In [128]:
np.mean(a, axis=0)

array([6.2, 8.2, 1.8])

In [129]:
a.mean(axis=0)

array([6.2, 8.2, 1.8])

In [130]:
np.mean(a, axis=1)

array([ 1.,  2.,  5., 13.,  6.])

In [131]:
a.mean(axis=1)

array([ 1.,  2.,  5., 13.,  6.])

In [132]:
np.median(a, axis=0)

array([4., 3., 1.])

In [133]:
np.median(a, axis=1)

array([1., 2., 4., 8., 1.])

In [134]:
a.var(axis=0, ddof=1)

array([ 37.2, 121.2,   1.7])

In [135]:
a.var(axis=1, ddof=1)

array([  0.,   1.,  13., 151.,  75.])

In [136]:
scipy.stats.gmean(a)

array([4.        , 3.73719282, 1.51571657])

In [137]:
scipy.stats.gmean(a, axis=0)

array([4.        , 3.73719282, 1.51571657])

In [138]:
scipy.stats.gmean(a, axis=None)

2.829705017016332

In [139]:
scipy.stats.describe(a, axis=None, ddof=1, bias=False)

DescribeResult(nobs=15, minmax=(1, 27), mean=5.4, variance=53.40000000000001, skewness=2.264965290423389, kurtosis=5.212690982795767)

## DataFrames

In [140]:
row_names = ['first', 'second', 'third', 'fourth', 'fifth']
col_names = ['A', 'B', 'C']
df = pd.DataFrame(a, index=row_names, columns=col_names)
df

A   B  C
first    1   1  1
second   2   3  1
third    4   9  2
fourth   8  27  4
fifth   16   1  1

In [141]:
df.mean()

A    6.2
B    8.2
C    1.8
dtype: float64

In [142]:
df.var()

A     37.2
B    121.2
C      1.7
dtype: float64

In [143]:
df.mean(axis=1)

first      1.0
second     2.0
third      5.0
fourth    13.0
fifth      6.0
dtype: float64

In [144]:
df['A'].var()

37.20000000000001

In [145]:
df.values

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [146]:
df.to_numpy()

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [147]:
df.describe()

A          B        C
count   5.00000   5.000000  5.00000
mean    6.20000   8.200000  1.80000
std     6.09918  11.009087  1.30384
min     1.00000   1.000000  1.00000
25%     2.00000   1.000000  1.00000
50%     4.00000   3.000000  1.00000
75%     8.00000   9.000000  2.00000
max    16.00000  27.000000  4.00000

In [148]:
df.describe().at['mean', 'A']

6.2

In [149]:
df.describe().at['50%', 'B']

3.0